# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicate',
            name='name',
            field=models.TextField(default='Example Syndicate'),
            preserve_default=False,
        ),
    ]
