# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20170212_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumbond',
            name='group_owned',
        ),
        migrations.AddField(
            model_name='premiumbond',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premiumbond',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
    ]
