# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0004_auto_20170214_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSyndicateWinnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnings', models.IntegerField()),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.Syndicate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
