# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0005_usersyndicatewinnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='syndicates',
        ),
        migrations.AddField(
            model_name='syndicate',
            name='members',
            field=models.ManyToManyField(to='bonds.UserProfile'),
        ),
    ]
