# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0008_auto_20170311_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.TextField(choices=[('EN', 'ENGLISH'), ('FR', 'FRENCH')], default='EN'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilepicture',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syndicate',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syndicate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
