# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0009_auto_20170317_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dummy_ans',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dummy_pwd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dummy_sq',
            field=models.TextField(default=''),
        ),
    ]
