# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0010_auto_20170318_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
    ]
