# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0011_auto_20170318_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_payout', models.IntegerField()),
                ('winning_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='premiumbond',
            name='group_owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='premiumbond',
            name='group_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonds.Syndicate'),
        ),
        migrations.AddField(
            model_name='bondreward',
            name='winning_bonds',
            field=models.ManyToManyField(to='bonds.PremiumBond'),
        ),
    ]
