# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0013_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dummy_ans',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dummy_pwd',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dummy_sq',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
