# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0015_productinfo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='productinfo',
            name='color',
            field=models.TextField(default='#00000'),
        ),
    ]
